version: '3.9'
services:
  <your service name>-frontend:
    container_name: <your service name>-frontend
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "3000:3000"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - <your Docker Network Name>
networks:
  <your Docker Network Name>:
    external: true