version: '3.9'
services:
  <your service name>-backend:
    container_name: <your service name>-backend
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://host.docker.internal:3306/<your DB NAME>?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: <your DB USERNAME>
      SPRING_DATASOURCE_PASSWORD: <your DB PASSWORD>
    ports:
      - "9999:9999"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - <your Docker Network Name>
networks:
  <your Docker Network Name>:
    external: true